/* Highly divisible triangular number */
/*
 * The sequence of triangle numbers is generated by adding 
 * the natural numbers. So the 7th triangle number would 
 * be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms 
 * would be:
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * Let us list the factors of the first seven triangle numbers:
 *      1: 1
 *      3: 1,3
 *      6: 1,2,3,6
 *     10: 1,2,5,10
 *     15: 1,3,5,15
 *     21: 1,3,7,21
 *     28: 1,2,4,7,14,28
 * We can see that 28 is the first triangle number to have over five divisors. 
 * What is the value of the first triangle number to have over five hundred divisors?
 */
package number;

public class HighlyDivisibleTriangularNumber {
  public static int triangleNum(int n){
		return n*(n+1)/2;
	}
	public static int factorNum(int n){
		int count = 0;
		for(int i = 1; i < java.lang.Math.sqrt(n); i++)
			if(n%i == 0)
				count +=2;
		if(n%java.lang.Math.sqrt(n) == 0)
			count ++;
		return count;
	}
	public static void main(String[] args) {
		int i,result;
		for(i = 2; factorNum(triangleNum(i)) < 500; i++);
		System.out.println(triangleNum(i));
		System.out.println(factorNum(triangleNum(i)));
	}
}
