/*
 * Pentagon numbers
 * Problem 44
 * Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

 * 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

 * It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

 * Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| 
 * is minimised; what is the value of D?
 */
package number;

public class PentagonNumbers {
  public static boolean isPentagonal(int n) {
//		double inverse = Math.sqrt(24 * n + 1) + 1;
//		return inverse % 6 == 0;
		double inverse = (Math.sqrt(24 * n + 1) + 1) / 6; // faster than the above;
		return inverse == (int) inverse;
	}
	public static void main(String[] args) {
		long start = System.nanoTime();
		int result = 0, i = 1;
		boolean notFound = true;
		while(notFound) {
			i++;
			int n = i * (3 * i - 1) / 2;
			for(int j = i - 1; j > 0; j--) {
				int m = j * (3 * j - 1) / 2;
				if(isPentagonal(n + m) && isPentagonal(n - m)) {
					notFound = false;
					result = n - m;
				}
			}
		}
		System.out.println(result);
		long time = System.nanoTime() - start;
		System.out.println("Runtime is " + time/1000/1000.0 + " ms.");
	}
}
