/*
 * Triangular, pentagonal, and hexagonal
 * Problem 45
 * 
 * Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

 * Triangle   	    Tn=n(n+1)/2	 	    1, 3, 6, 10, 15, ...
 * Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
 * Hexagonal	 	Hn=n(2n−1)	 	    1, 6, 15, 28, 45, ...
 * It can be verified that T285 = P165 = H143 = 40755.

 * Find the next triangle number that is also pentagonal and hexagonal.
 */
package number;

public class TriangularPentagonalHexagonal {
	public static boolean isPentagonal(long hexagonal) {
		double inverse = (Math.sqrt(24 * hexagonal + 1) + 1) / 6;
		return inverse == (int)inverse;
	}
	public static void main(String[] args) {
		// Since the set of hexagonal numbers is a subset of triangle numbers, we just need 
		//to check if a hexagonal number is pentagonal.
		long start = System.nanoTime();
		int i = 143;
		long hexagonal = 0;	
		while(!isPentagonal(hexagonal)) {
			i++;
			hexagonal = i * (2 * i - 1);
		}
		System.out.println(hexagonal);
		long time = System.nanoTime() - start;
		System.out.println("Runtime is " + time/1000/1000.0 + " ms.");
	}
}
